/* Generated by re2c 4.2 on Sat May  3 08:24:57 2025 */
#line 1 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
#include <stdlib.h>
#include <string.h>

#include "lexer.h"

#line 9 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
#define YYMAXFILL 11
#line 6 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"

#define SIZE 64 * 1024

struct lex_token_stream_t {
    tok_queue_t* queue;
    int value;
};

struct lex_input_t {
    FILE* file;
    unsigned char buf[SIZE + YYMAXFILL];
    unsigned char* limit;
    unsigned char* current;
    unsigned char* marker;
    unsigned char* token;
    int eof;
};

lex_input_t* lex_open(FILE* file) {
    lex_input_t* input = (lex_input_t*) malloc(sizeof(lex_input_t));
    if (input == NULL) {
        return NULL;
    }
    input->file = file;
    input->limit = input->buf + SIZE;
    input->current = input->limit;
    input->marker = input->limit;
    input->token = input->limit;
    input->eof = 0;
    return input;
}

void lex_close_input(lex_input_t* input) {
    free(input);
}

int fill(lex_input_t* input, size_t size) {
    if (input->eof) {
        return 0;
    }
    const size_t free = input->token - input->buf;
    if (free < size) {
        return 0;
    }
    memmove(input->buf, input->token, input->limit - input->token);
    input->limit -= free;
    input->current -= free;
    input->marker -= free;
    input->token -= free;
    input->limit += fread(input->limit, 1, free, input->file);
    if (input->limit < input->buf + SIZE) {
        input->eof = 1;
        memset(input->limit, 0, YYMAXFILL);
        input->limit += YYMAXFILL;
    }
    return 1;
}

void _append_floating_point_literal(lex_token_stream_t* stream, int type, double value) {
    append_float_tok_queue(stream->queue, type, value);
}

void _append_decimal_literal(lex_token_stream_t* stream, int type, long long value) {
    append_int_tok_queue(stream->queue, type, value);
}

void _append_bool_literal(lex_token_stream_t* stream, int type) {
    append_int_tok_queue(stream->queue, type, type == TRUE_VALUE);
}

void _append_str_literal(lex_token_stream_t* stream, int type, char* str, int len) {
    append_str_tok_queue(stream->queue, type, str, len);
}

void _append_token(lex_token_stream_t* stream, int type) {
    append_tok_queue(stream->queue, type);
}

double _parse_float_from_re2c(lex_input_t* input) {
    const int len = (int) (input->current - input->token);
    char buf[len + 1];
    strncpy(buf, (char*) input->token, len);
    buf[len] = 0;
    return atof(buf);
}

long long _parse_dec_from_re2c(lex_input_t* input) {
    const int len = (int) (input->current - input->token);
    char buf[len + 1];
    strncpy(buf, (char*) input->token, len);
    buf[len] = 0;
    return atoll(buf);
}

long long _parse_hex_from_re2c(lex_input_t* input) {
    const int len = (int) (input->current - input->token);
    char buf[len + 1];
    strncpy(buf, (char*) input->token, len);
    buf[len] = 0;
    return strtoll(buf, NULL, 16);
}

char* _parse_str_from_re2c(lex_input_t* input) {
    unsigned char quote = input->current[-1];
    unsigned char* start = input->token;
    int length;
    for (length = 1;;) {
        length++;
        
#line 121 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
{
	char yych;
	++start;
#line 118 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ 
                unsigned char c = start[0];
                if (c == quote) break;
                continue;
            }
#line 131 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
}
#line 123 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"

    }

    char buf[length];
    int index = 0;
    buf[index++] = quote;
    for (unsigned char c = quote;;) {
        input->token = input->current;
        
#line 143 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
{
	char yych;
	if ((input->limit - input->current) < 2) if (!fill(input, 2)) { return NULL; }
	yych = *input->current;
	switch (yych) {
		case '\n': goto yy3;
		case '\\': goto yy5;
		default: goto yy2;
	}
yy2:
	++input->current;
#line 140 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{
                c = input->token[0];
                buf[index++] = c;
                if (c == quote) break;
                continue;
            }
#line 162 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy3:
	++input->current;
yy4:
#line 159 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ return NULL; }
#line 168 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy5:
	yych = *++input->current;
	switch (yych) {
		case '"':
		case '\'':
		case '`': goto yy6;
		case '\\': goto yy7;
		case 'b': goto yy8;
		case 'f': goto yy9;
		case 'n': goto yy10;
		case 'r': goto yy11;
		case 't': goto yy12;
		default: goto yy4;
	}
yy6:
	++input->current;
#line 152 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{
                if (input->token[1] != quote) {
                    buf[index++] = input->token[0];
                }
                buf[index++] = input->token[1];
                continue;
            }
#line 193 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy7:
	++input->current;
#line 151 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ buf[index++] = '\\'; continue; }
#line 198 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy8:
	++input->current;
#line 150 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ buf[index++] = '\b'; continue; }
#line 203 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy9:
	++input->current;
#line 149 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ buf[index++] = '\f'; continue; }
#line 208 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy10:
	++input->current;
#line 147 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ buf[index++] = '\n'; continue; }
#line 213 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy11:
	++input->current;
#line 146 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ buf[index++] = '\r'; continue; }
#line 218 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy12:
	++input->current;
#line 148 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ buf[index++] = '\t'; continue; }
#line 223 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
}
#line 160 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"

    }
    buf[index] = 0;
    return (char*) strdup(buf);
}

lex_token_stream_t* lex_run(lex_input_t* input) {
    lex_token_stream_t* stream = (lex_token_stream_t*) malloc(sizeof(lex_token_stream_t));
    if (stream == NULL) {
        return NULL;
    }
    stream->queue = allocate_tok_queue();
    stream->value = ERROR;
    for (;;) {
        input->token = input->current;
        
#line 242 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
{
	char yych;
	unsigned int yyaccept = 0;
	if ((input->limit - input->current) < 11) if (!fill(input, 11)) { stream->value = 0; return stream; }
	yych = *input->current;
	switch (yych) {
		case 0x00: goto yy14;
		case '\t':
		case '\n':
		case '\v':
		case '\r':
		case ' ': goto yy17;
		case '!': goto yy19;
		case '"':
		case '\'':
		case '`': goto yy20;
		case '%': goto yy21;
		case '&': goto yy23;
		case '(': goto yy25;
		case ')': goto yy26;
		case '*': goto yy27;
		case '+': goto yy29;
		case ',': goto yy31;
		case '-': goto yy32;
		case '.': goto yy34;
		case '/': goto yy36;
		case '0': goto yy38;
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy39;
		case '<': goto yy41;
		case '=': goto yy43;
		case '>': goto yy44;
		case '?': goto yy46;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'g':
		case 'h':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'q':
		case 'y':
		case 'z': goto yy47;
		case '[': goto yy50;
		case ']': goto yy51;
		case '^': goto yy52;
		case 'a': goto yy54;
		case 'b': goto yy55;
		case 'c': goto yy56;
		case 'd': goto yy57;
		case 'e': goto yy58;
		case 'f': goto yy59;
		case 'i': goto yy60;
		case 'n': goto yy61;
		case 'o': goto yy62;
		case 'p': goto yy63;
		case 'r': goto yy64;
		case 's': goto yy65;
		case 't': goto yy66;
		case 'u': goto yy67;
		case 'v': goto yy68;
		case 'w': goto yy69;
		case 'x': goto yy70;
		case '{': goto yy71;
		case '|': goto yy72;
		case '}': goto yy74;
		case '~': goto yy75;
		default: goto yy15;
	}
yy14:
	++input->current;
#line 185 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{
                stream->value = input->limit - input->token == YYMAXFILL;
                break;
            }
#line 352 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy15:
	++input->current;
yy16:
#line 321 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ 
                lex_close_token_stream(stream);
                return NULL;
            }
#line 361 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy17:
	yyaccept = 0;
	input->marker = ++input->current;
	if (input->limit <= input->current) if (!fill(input, 1)) { stream->value = 0; return stream; }
	yych = *input->current;
	switch (yych) {
		case '\t':
		case '\n':
		case '\v':
		case '\r':
		case ' ': goto yy17;
		case '/': goto yy77;
		default: goto yy18;
	}
yy18:
#line 192 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ continue; }
#line 379 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy19:
	++input->current;
#line 305 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, NOT_OPER); continue; }
#line 384 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy20:
	++input->current;
#line 195 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{
                char* str = _parse_str_from_re2c(input);
                if (str == NULL) {
                    stream->value = ERROR;
                    return stream;
                }
                int len = strlen(str);
                _append_str_literal(stream, STRING_LIT, str, len);
                free(str);
                continue;
            }
#line 399 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy21:
	yych = *++input->current;
	switch (yych) {
		case '=': goto yy79;
		default: goto yy22;
	}
yy22:
#line 290 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, MOD_OPER); continue; }
#line 409 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy23:
	yych = *++input->current;
	switch (yych) {
		case '&': goto yy80;
		default: goto yy24;
	}
yy24:
#line 307 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, BIT_AND_OPER); continue; }
#line 419 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy25:
	++input->current;
#line 225 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, O_PARENTHESES); continue; }
#line 424 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy26:
	++input->current;
#line 226 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, C_PARENTHESES); continue; }
#line 429 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy27:
	yych = *++input->current;
	switch (yych) {
		case '*': goto yy82;
		case '=': goto yy83;
		default: goto yy28;
	}
yy28:
#line 288 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, MUL_OPER); continue; }
#line 440 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy29:
	yych = *++input->current;
	switch (yych) {
		case '+': goto yy84;
		case '=': goto yy85;
		default: goto yy30;
	}
yy30:
#line 286 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, ADD_OPER); continue; }
#line 451 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy31:
	++input->current;
#line 232 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, COMMA); continue; }
#line 456 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy32:
	yych = *++input->current;
	switch (yych) {
		case '-': goto yy86;
		case '=': goto yy87;
		default: goto yy33;
	}
yy33:
#line 287 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, SUB_OPER); continue; }
#line 467 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy34:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy88;
		default: goto yy35;
	}
yy35:
#line 231 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, DOT); continue; }
#line 486 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy36:
	yych = *++input->current;
	switch (yych) {
		case '/': goto yy90;
		case '=': goto yy91;
		default: goto yy37;
	}
yy37:
#line 289 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, DIV_OPER); continue; }
#line 497 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy38:
	yyaccept = 1;
	yych = *(input->marker = ++input->current);
	switch (yych) {
		case '.': goto yy88;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy92;
		case 'X':
		case 'x': goto yy93;
		default: goto yy16;
	}
yy39:
	++input->current;
	if (input->limit <= input->current) if (!fill(input, 1)) { stream->value = 0; return stream; }
	yych = *input->current;
	switch (yych) {
		case '.': goto yy88;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy39;
		default: goto yy40;
	}
yy40:
#line 208 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ // Decimal
                long long value = _parse_dec_from_re2c(input);
                _append_decimal_literal(stream, INTEGER, value);
                continue;
            }
#line 542 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy41:
	yych = *++input->current;
	switch (yych) {
		case '<': goto yy94;
		case '=': goto yy96;
		default: goto yy42;
	}
yy42:
#line 300 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, LT_OPER); continue; }
#line 553 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy43:
	++input->current;
#line 285 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, EQ_OPER); continue; }
#line 558 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy44:
	yych = *++input->current;
	switch (yych) {
		case '=': goto yy97;
		case '>': goto yy98;
		default: goto yy45;
	}
yy45:
#line 299 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, GT_OPER); continue; }
#line 569 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy46:
	++input->current;
#line 306 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, TERNARY_OPER); continue; }
#line 574 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy47:
	++input->current;
	if (input->limit <= input->current) if (!fill(input, 1)) { stream->value = 0; return stream; }
	yych = *input->current;
yy48:
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy49;
	}
yy49:
#line 315 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{
                int len = (int) (input->current - input->token);
                _append_str_literal(stream, IDENTIFIER, (char*) input->token, len);
                continue;
            }
#line 653 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy50:
	++input->current;
#line 229 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, O_BRACKET); continue; }
#line 658 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy51:
	++input->current;
#line 230 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, C_BRACKET); continue; }
#line 663 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy52:
	++input->current;
yy53:
#line 309 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, BIT_XOR_OPER); continue; }
#line 669 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy54:
	yych = *++input->current;
	switch (yych) {
		case 'b': goto yy100;
		case 'n': goto yy101;
		case 's': goto yy102;
		default: goto yy48;
	}
yy55:
	yych = *++input->current;
	switch (yych) {
		case 'i': goto yy103;
		case 'o': goto yy104;
		case 'r': goto yy105;
		default: goto yy48;
	}
yy56:
	yych = *++input->current;
	switch (yych) {
		case 'h': goto yy106;
		case 'l': goto yy107;
		case 'o': goto yy108;
		default: goto yy48;
	}
yy57:
	yych = *++input->current;
	switch (yych) {
		case 'e': goto yy109;
		default: goto yy48;
	}
yy58:
	yych = *++input->current;
	switch (yych) {
		case 'l': goto yy110;
		case 'n': goto yy111;
		case 'x': goto yy112;
		default: goto yy48;
	}
yy59:
	yych = *++input->current;
	switch (yych) {
		case 'a': goto yy113;
		case 'i': goto yy114;
		case 'l': goto yy115;
		case 'o': goto yy116;
		case 'u': goto yy117;
		default: goto yy48;
	}
yy60:
	yych = *++input->current;
	switch (yych) {
		case 'f': goto yy118;
		case 'm': goto yy120;
		case 'n': goto yy121;
		case 's': goto yy123;
		default: goto yy48;
	}
yy61:
	yych = *++input->current;
	switch (yych) {
		case 'e': goto yy125;
		case 'u': goto yy126;
		default: goto yy48;
	}
yy62:
	yych = *++input->current;
	switch (yych) {
		case 'r': goto yy127;
		default: goto yy48;
	}
yy63:
	yych = *++input->current;
	switch (yych) {
		case 'r': goto yy129;
		default: goto yy48;
	}
yy64:
	yych = *++input->current;
	switch (yych) {
		case 'a': goto yy130;
		case 'e': goto yy131;
		default: goto yy48;
	}
yy65:
	yych = *++input->current;
	switch (yych) {
		case 'h': goto yy132;
		case 't': goto yy133;
		default: goto yy48;
	}
yy66:
	yych = *++input->current;
	switch (yych) {
		case 'h': goto yy134;
		case 'r': goto yy135;
		default: goto yy48;
	}
yy67:
	yych = *++input->current;
	switch (yych) {
		case 'i': goto yy136;
		case 'n': goto yy137;
		default: goto yy48;
	}
yy68:
	yych = *++input->current;
	switch (yych) {
		case 'o': goto yy138;
		default: goto yy48;
	}
yy69:
	yych = *++input->current;
	switch (yych) {
		case 'h': goto yy139;
		default: goto yy48;
	}
yy70:
	yych = *++input->current;
	switch (yych) {
		case 'o': goto yy140;
		default: goto yy48;
	}
yy71:
	++input->current;
#line 227 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, O_C_BRACKET); continue; }
#line 796 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy72:
	yych = *++input->current;
	switch (yych) {
		case '|': goto yy141;
		default: goto yy73;
	}
yy73:
#line 308 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, BIT_OR_OPER); continue; }
#line 806 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy74:
	++input->current;
#line 228 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, C_C_BRACKET); continue; }
#line 811 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy75:
	++input->current;
yy76:
#line 310 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, BIT_NOT_OPER); continue; }
#line 817 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy77:
	++input->current;
	if (input->limit <= input->current) if (!fill(input, 1)) { stream->value = 0; return stream; }
	yych = *input->current;
	switch (yych) {
		case '/': goto yy90;
		default: goto yy78;
	}
yy78:
	input->current = input->marker;
	if (yyaccept == 0) goto yy18;
	else goto yy16;
yy79:
	++input->current;
#line 297 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, MOD_EQ_OPER); continue; }
#line 834 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy80:
	++input->current;
yy81:
#line 303 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, AND_OPER); continue; }
#line 840 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy82:
	++input->current;
#line 298 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, POW_OPER); continue; }
#line 845 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy83:
	++input->current;
#line 295 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, MUL_EQ_OPER); continue; }
#line 850 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy84:
	++input->current;
#line 291 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, INCR_OPER); continue; }
#line 855 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy85:
	++input->current;
#line 293 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, ADD_EQ_OPER); continue; }
#line 860 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy86:
	++input->current;
#line 292 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, DECR_OPER); continue; }
#line 865 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy87:
	++input->current;
#line 294 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, SUB_EQ_OPER); continue; }
#line 870 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy88:
	++input->current;
	if (input->limit <= input->current) if (!fill(input, 1)) { stream->value = 0; return stream; }
	yych = *input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy88;
		default: goto yy89;
	}
yy89:
#line 218 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ // Float
                double value = _parse_float_from_re2c(input);
                _append_floating_point_literal(stream, FLOATING_POINT, value);
                continue;
            }
#line 895 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy90:
	++input->current;
	if (input->limit <= input->current) if (!fill(input, 1)) { stream->value = 0; return stream; }
	yych = *input->current;
	switch (yych) {
		case '\n': goto yy17;
		default: goto yy90;
	}
yy91:
	++input->current;
#line 296 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, DIV_EQ_OPER); continue; }
#line 908 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy92:
	++input->current;
	if (input->limit <= input->current) if (!fill(input, 1)) { stream->value = 0; return stream; }
	yych = *input->current;
	switch (yych) {
		case '.': goto yy88;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy92;
		default: goto yy78;
	}
yy93:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy142;
		default: goto yy78;
	}
yy94:
	++input->current;
yy95:
#line 312 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, BIT_SHL_OPER); continue; }
#line 959 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy96:
	++input->current;
#line 302 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, LT_EQ_OPER); continue; }
#line 964 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy97:
	++input->current;
#line 301 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, GT_EQ_OPER); continue; }
#line 969 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy98:
	++input->current;
yy99:
#line 311 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, BIT_SHR_OPER); continue; }
#line 975 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy100:
	yych = *++input->current;
	switch (yych) {
		case 's': goto yy144;
		default: goto yy48;
	}
yy101:
	yych = *++input->current;
	switch (yych) {
		case 'd': goto yy145;
		default: goto yy48;
	}
yy102:
	yych = *++input->current;
	switch (yych) {
		case 's': goto yy146;
		case 'y': goto yy147;
		default: goto yy48;
	}
yy103:
	yych = *++input->current;
	switch (yych) {
		case 't': goto yy148;
		default: goto yy48;
	}
yy104:
	yych = *++input->current;
	switch (yych) {
		case 'o': goto yy149;
		default: goto yy48;
	}
yy105:
	yych = *++input->current;
	switch (yych) {
		case 'e': goto yy150;
		default: goto yy48;
	}
yy106:
	yych = *++input->current;
	switch (yych) {
		case 'a': goto yy151;
		default: goto yy48;
	}
yy107:
	yych = *++input->current;
	switch (yych) {
		case 'a': goto yy152;
		default: goto yy48;
	}
yy108:
	yych = *++input->current;
	switch (yych) {
		case 'm': goto yy153;
		case 'n': goto yy154;
		default: goto yy48;
	}
yy109:
	yych = *++input->current;
	switch (yych) {
		case 'f': goto yy155;
		default: goto yy48;
	}
yy110:
	yych = *++input->current;
	switch (yych) {
		case 's': goto yy156;
		default: goto yy48;
	}
yy111:
	yych = *++input->current;
	switch (yych) {
		case 'u': goto yy157;
		default: goto yy48;
	}
yy112:
	yych = *++input->current;
	switch (yych) {
		case 't': goto yy158;
		default: goto yy48;
	}
yy113:
	yych = *++input->current;
	switch (yych) {
		case 'l': goto yy159;
		default: goto yy48;
	}
yy114:
	yych = *++input->current;
	switch (yych) {
		case 'n': goto yy160;
		default: goto yy48;
	}
yy115:
	yych = *++input->current;
	switch (yych) {
		case 'o': goto yy161;
		default: goto yy48;
	}
yy116:
	yych = *++input->current;
	switch (yych) {
		case 'r': goto yy162;
		default: goto yy48;
	}
yy117:
	yych = *++input->current;
	switch (yych) {
		case 'n': goto yy164;
		case 't': goto yy165;
		default: goto yy48;
	}
yy118:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy119;
	}
yy119:
#line 249 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, IF); continue; }
#line 1158 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy120:
	yych = *++input->current;
	switch (yych) {
		case 'p': goto yy166;
		default: goto yy48;
	}
yy121:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		case 'c': goto yy167;
		case 't': goto yy168;
		default: goto yy122;
	}
yy122:
#line 252 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, IN); continue; }
#line 1236 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy123:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy124;
	}
yy124:
#line 257 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, IS); continue; }
#line 1308 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy125:
	yych = *++input->current;
	switch (yych) {
		case 'w': goto yy169;
		default: goto yy48;
	}
yy126:
	yych = *++input->current;
	switch (yych) {
		case 'l': goto yy171;
		default: goto yy48;
	}
yy127:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy128;
	}
yy128:
#line 304 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, OR_OPER); continue; }
#line 1392 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy129:
	yych = *++input->current;
	switch (yych) {
		case 'i': goto yy172;
		case 'o': goto yy173;
		default: goto yy48;
	}
yy130:
	yych = *++input->current;
	switch (yych) {
		case 'n': goto yy174;
		default: goto yy48;
	}
yy131:
	yych = *++input->current;
	switch (yych) {
		case 't': goto yy175;
		default: goto yy48;
	}
yy132:
	yych = *++input->current;
	switch (yych) {
		case 'l': goto yy176;
		case 'r': goto yy177;
		default: goto yy48;
	}
yy133:
	yych = *++input->current;
	switch (yych) {
		case 'r': goto yy178;
		default: goto yy48;
	}
yy134:
	yych = *++input->current;
	switch (yych) {
		case 'i': goto yy179;
		default: goto yy48;
	}
yy135:
	yych = *++input->current;
	switch (yych) {
		case 'u': goto yy180;
		default: goto yy48;
	}
yy136:
	yych = *++input->current;
	switch (yych) {
		case 'n': goto yy181;
		default: goto yy48;
	}
yy137:
	yych = *++input->current;
	switch (yych) {
		case 's': goto yy182;
		default: goto yy48;
	}
yy138:
	yych = *++input->current;
	switch (yych) {
		case 'i': goto yy183;
		default: goto yy48;
	}
yy139:
	yych = *++input->current;
	switch (yych) {
		case 'i': goto yy184;
		default: goto yy48;
	}
yy140:
	yych = *++input->current;
	switch (yych) {
		case 'r': goto yy185;
		default: goto yy48;
	}
yy141:
	++input->current;
	goto yy128;
yy142:
	++input->current;
	if (input->limit <= input->current) if (!fill(input, 1)) { stream->value = 0; return stream; }
	yych = *input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f': goto yy142;
		default: goto yy143;
	}
yy143:
#line 213 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ // Hex
                long long value = _parse_hex_from_re2c(input);
                _append_decimal_literal(stream, INTEGER, value);
                continue;
            }
#line 1506 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy144:
	yych = *++input->current;
	switch (yych) {
		case 't': goto yy186;
		default: goto yy48;
	}
yy145:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy81;
	}
yy146:
	yych = *++input->current;
	switch (yych) {
		case 'e': goto yy187;
		default: goto yy48;
	}
yy147:
	yych = *++input->current;
	switch (yych) {
		case 'n': goto yy188;
		default: goto yy48;
	}
yy148:
	yych = *++input->current;
	switch (yych) {
		case 'a': goto yy189;
		case 'o': goto yy190;
		default: goto yy48;
	}
yy149:
	yych = *++input->current;
	switch (yych) {
		case 'l': goto yy191;
		default: goto yy48;
	}
yy150:
	yych = *++input->current;
	switch (yych) {
		case 'a': goto yy193;
		default: goto yy48;
	}
yy151:
	yych = *++input->current;
	switch (yych) {
		case 'r': goto yy194;
		default: goto yy48;
	}
yy152:
	yych = *++input->current;
	switch (yych) {
		case 's': goto yy196;
		default: goto yy48;
	}
yy153:
	yych = *++input->current;
	switch (yych) {
		case 'p': goto yy197;
		default: goto yy48;
	}
yy154:
	yych = *++input->current;
	switch (yych) {
		case 't': goto yy198;
		default: goto yy48;
	}
yy155:
	yych = *++input->current;
	switch (yych) {
		case 'e': goto yy199;
		default: goto yy48;
	}
yy156:
	yych = *++input->current;
	switch (yych) {
		case 'e': goto yy200;
		default: goto yy48;
	}
yy157:
	yych = *++input->current;
	switch (yych) {
		case 'm': goto yy202;
		default: goto yy48;
	}
yy158:
	yych = *++input->current;
	switch (yych) {
		case 'e': goto yy204;
		default: goto yy48;
	}
yy159:
	yych = *++input->current;
	switch (yych) {
		case 's': goto yy205;
		default: goto yy48;
	}
yy160:
	yych = *++input->current;
	switch (yych) {
		case 'a': goto yy206;
		default: goto yy48;
	}
yy161:
	yych = *++input->current;
	switch (yych) {
		case 'a': goto yy207;
		default: goto yy48;
	}
yy162:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy163;
	}
yy163:
#line 251 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, FOR); continue; }
#line 1749 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy164:
	yych = *++input->current;
	switch (yych) {
		case 'c': goto yy208;
		default: goto yy48;
	}
yy165:
	yych = *++input->current;
	switch (yych) {
		case 'u': goto yy209;
		default: goto yy48;
	}
yy166:
	yych = *++input->current;
	switch (yych) {
		case 'l': goto yy210;
		default: goto yy48;
	}
yy167:
	yych = *++input->current;
	switch (yych) {
		case 'l': goto yy211;
		default: goto yy48;
	}
yy168:
	yych = *++input->current;
	switch (yych) {
		case '1': goto yy212;
		case '3': goto yy213;
		case '6': goto yy214;
		case '8': goto yy215;
		case 'e': goto yy217;
		default: goto yy48;
	}
yy169:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy170;
	}
yy170:
#line 241 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, NEW); continue; }
#line 1855 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy171:
	yych = *++input->current;
	switch (yych) {
		case 'l': goto yy218;
		default: goto yy48;
	}
yy172:
	yych = *++input->current;
	switch (yych) {
		case 'v': goto yy220;
		default: goto yy48;
	}
yy173:
	yych = *++input->current;
	switch (yych) {
		case 't': goto yy221;
		default: goto yy48;
	}
yy174:
	yych = *++input->current;
	switch (yych) {
		case 'g': goto yy222;
		default: goto yy48;
	}
yy175:
	yych = *++input->current;
	switch (yych) {
		case 'u': goto yy223;
		default: goto yy48;
	}
yy176:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy95;
	}
yy177:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy99;
	}
yy178:
	yych = *++input->current;
	switch (yych) {
		case 'i': goto yy224;
		default: goto yy48;
	}
yy179:
	yych = *++input->current;
	switch (yych) {
		case 's': goto yy225;
		default: goto yy48;
	}
yy180:
	yych = *++input->current;
	switch (yych) {
		case 'e': goto yy227;
		default: goto yy48;
	}
yy181:
	yych = *++input->current;
	switch (yych) {
		case 't': goto yy229;
		default: goto yy48;
	}
yy182:
	yych = *++input->current;
	switch (yych) {
		case 'a': goto yy230;
		default: goto yy48;
	}
yy183:
	yych = *++input->current;
	switch (yych) {
		case 'd': goto yy231;
		default: goto yy48;
	}
yy184:
	yych = *++input->current;
	switch (yych) {
		case 'l': goto yy233;
		default: goto yy48;
	}
yy185:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy53;
	}
yy186:
	yych = *++input->current;
	switch (yych) {
		case 'r': goto yy234;
		default: goto yy48;
	}
yy187:
	yych = *++input->current;
	switch (yych) {
		case 'r': goto yy235;
		default: goto yy48;
	}
yy188:
	yych = *++input->current;
	switch (yych) {
		case 'c': goto yy236;
		default: goto yy48;
	}
yy189:
	yych = *++input->current;
	switch (yych) {
		case 'n': goto yy238;
		default: goto yy48;
	}
yy190:
	yych = *++input->current;
	switch (yych) {
		case 'r': goto yy239;
		default: goto yy48;
	}
yy191:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy192;
	}
yy192:
#line 275 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, BOOL); continue; }
#line 2233 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy193:
	yych = *++input->current;
	switch (yych) {
		case 'k': goto yy240;
		default: goto yy48;
	}
yy194:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy195;
	}
yy195:
#line 274 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, CHAR); continue; }
#line 2311 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy196:
	yych = *++input->current;
	switch (yych) {
		case 's': goto yy242;
		default: goto yy48;
	}
yy197:
	yych = *++input->current;
	switch (yych) {
		case 'l': goto yy244;
		default: goto yy48;
	}
yy198:
	yych = *++input->current;
	switch (yych) {
		case 'i': goto yy245;
		default: goto yy48;
	}
yy199:
	yych = *++input->current;
	switch (yych) {
		case 'r': goto yy246;
		default: goto yy48;
	}
yy200:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy201;
	}
yy201:
#line 250 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, ELSE); continue; }
#line 2407 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy202:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy203;
	}
yy203:
#line 239 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, ENUM); continue; }
#line 2479 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy204:
	yych = *++input->current;
	switch (yych) {
		case 'n': goto yy248;
		default: goto yy48;
	}
yy205:
	yych = *++input->current;
	switch (yych) {
		case 'e': goto yy249;
		default: goto yy48;
	}
yy206:
	yych = *++input->current;
	switch (yych) {
		case 'l': goto yy251;
		default: goto yy48;
	}
yy207:
	yych = *++input->current;
	switch (yych) {
		case 't': goto yy253;
		default: goto yy48;
	}
yy208:
	yych = *++input->current;
	switch (yych) {
		case 't': goto yy254;
		default: goto yy48;
	}
yy209:
	yych = *++input->current;
	switch (yych) {
		case 'r': goto yy255;
		default: goto yy48;
	}
yy210:
	yych = *++input->current;
	switch (yych) {
		case 'e': goto yy256;
		default: goto yy48;
	}
yy211:
	yych = *++input->current;
	switch (yych) {
		case 'u': goto yy257;
		default: goto yy48;
	}
yy212:
	yych = *++input->current;
	switch (yych) {
		case '6': goto yy258;
		default: goto yy48;
	}
yy213:
	yych = *++input->current;
	switch (yych) {
		case '2': goto yy260;
		default: goto yy48;
	}
yy214:
	yych = *++input->current;
	switch (yych) {
		case '4': goto yy262;
		default: goto yy48;
	}
yy215:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy216;
	}
yy216:
#line 264 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, INT8); continue; }
#line 2617 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy217:
	yych = *++input->current;
	switch (yych) {
		case 'r': goto yy264;
		default: goto yy48;
	}
yy218:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy219;
	}
yy219:
#line 282 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_bool_literal(stream, NULL_VALUE); continue; }
#line 2695 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy220:
	yych = *++input->current;
	switch (yych) {
		case 'a': goto yy265;
		default: goto yy48;
	}
yy221:
	yych = *++input->current;
	switch (yych) {
		case 'e': goto yy266;
		default: goto yy48;
	}
yy222:
	yych = *++input->current;
	switch (yych) {
		case 'e': goto yy267;
		default: goto yy48;
	}
yy223:
	yych = *++input->current;
	switch (yych) {
		case 'r': goto yy269;
		default: goto yy48;
	}
yy224:
	yych = *++input->current;
	switch (yych) {
		case 'n': goto yy270;
		default: goto yy48;
	}
yy225:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy226;
	}
yy226:
#line 247 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, THIS); continue; }
#line 2797 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy227:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy228;
	}
yy228:
#line 280 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_bool_literal(stream, TRUE_VALUE); continue; }
#line 2869 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy229:
	yych = *++input->current;
	switch (yych) {
		case '1': goto yy271;
		case '3': goto yy272;
		case '6': goto yy273;
		case '8': goto yy274;
		default: goto yy48;
	}
yy230:
	yych = *++input->current;
	switch (yych) {
		case 'f': goto yy276;
		default: goto yy48;
	}
yy231:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy232;
	}
yy232:
#line 277 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, VOID); continue; }
#line 2956 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy233:
	yych = *++input->current;
	switch (yych) {
		case 'e': goto yy277;
		default: goto yy48;
	}
yy234:
	yych = *++input->current;
	switch (yych) {
		case 'a': goto yy279;
		default: goto yy48;
	}
yy235:
	yych = *++input->current;
	switch (yych) {
		case 't': goto yy280;
		default: goto yy48;
	}
yy236:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy237;
	}
yy237:
#line 258 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, ASYNC); continue; }
#line 3046 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy238:
	yych = *++input->current;
	switch (yych) {
		case 'd': goto yy282;
		default: goto yy48;
	}
yy239:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy73;
	}
yy240:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy241;
	}
yy241:
#line 256 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, BREAK); continue; }
#line 3192 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy242:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy243;
	}
yy243:
#line 238 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, CLASS); continue; }
#line 3264 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy244:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy76;
	}
yy245:
	yych = *++input->current;
	switch (yych) {
		case 'n': goto yy283;
		default: goto yy48;
	}
yy246:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy247;
	}
yy247:
#line 261 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, DEFER); continue; }
#line 3410 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy248:
	yych = *++input->current;
	switch (yych) {
		case 'd': goto yy284;
		default: goto yy48;
	}
yy249:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy250;
	}
yy250:
#line 281 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_bool_literal(stream, FALSE_VALUE); continue; }
#line 3488 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy251:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy252;
	}
yy252:
#line 245 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, FINAL); continue; }
#line 3560 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy253:
	yych = *++input->current;
	switch (yych) {
		case '3': goto yy285;
		case '6': goto yy286;
		default: goto yy48;
	}
yy254:
	yych = *++input->current;
	switch (yych) {
		case 'i': goto yy287;
		default: goto yy48;
	}
yy255:
	yych = *++input->current;
	switch (yych) {
		case 'e': goto yy288;
		default: goto yy48;
	}
yy256:
	yych = *++input->current;
	switch (yych) {
		case 'm': goto yy290;
		default: goto yy48;
	}
yy257:
	yych = *++input->current;
	switch (yych) {
		case 'd': goto yy291;
		default: goto yy48;
	}
yy258:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy259;
	}
yy259:
#line 265 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, INT16); continue; }
#line 3663 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy260:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy261;
	}
yy261:
#line 266 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, INT32); continue; }
#line 3735 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy262:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy263;
	}
yy263:
#line 267 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, INT64); continue; }
#line 3807 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy264:
	yych = *++input->current;
	switch (yych) {
		case 'f': goto yy292;
		default: goto yy48;
	}
yy265:
	yych = *++input->current;
	switch (yych) {
		case 't': goto yy293;
		default: goto yy48;
	}
yy266:
	yych = *++input->current;
	switch (yych) {
		case 'c': goto yy294;
		default: goto yy48;
	}
yy267:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy268;
	}
yy268:
#line 253 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, RANGE); continue; }
#line 3897 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy269:
	yych = *++input->current;
	switch (yych) {
		case 'n': goto yy295;
		default: goto yy48;
	}
yy270:
	yych = *++input->current;
	switch (yych) {
		case 'g': goto yy297;
		default: goto yy48;
	}
yy271:
	yych = *++input->current;
	switch (yych) {
		case '6': goto yy299;
		default: goto yy48;
	}
yy272:
	yych = *++input->current;
	switch (yych) {
		case '2': goto yy301;
		default: goto yy48;
	}
yy273:
	yych = *++input->current;
	switch (yych) {
		case '4': goto yy303;
		default: goto yy48;
	}
yy274:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy275;
	}
yy275:
#line 268 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, UINT8); continue; }
#line 3999 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy276:
	yych = *++input->current;
	switch (yych) {
		case 'e': goto yy305;
		default: goto yy48;
	}
yy277:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy278;
	}
yy278:
#line 254 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, WHILE); continue; }
#line 4077 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy279:
	yych = *++input->current;
	switch (yych) {
		case 'c': goto yy307;
		default: goto yy48;
	}
yy280:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy281;
	}
yy281:
#line 246 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, ASSERT); continue; }
#line 4155 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy282:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy24;
	}
yy283:
	yych = *++input->current;
	switch (yych) {
		case 'u': goto yy308;
		default: goto yy48;
	}
yy284:
	yych = *++input->current;
	switch (yych) {
		case 's': goto yy309;
		default: goto yy48;
	}
yy285:
	yych = *++input->current;
	switch (yych) {
		case '2': goto yy311;
		default: goto yy48;
	}
yy286:
	yych = *++input->current;
	switch (yych) {
		case '4': goto yy313;
		default: goto yy48;
	}
yy287:
	yych = *++input->current;
	switch (yych) {
		case 'o': goto yy315;
		default: goto yy48;
	}
yy288:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy289;
	}
yy289:
#line 259 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, FUTURE); continue; }
#line 4325 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy290:
	yych = *++input->current;
	switch (yych) {
		case 'e': goto yy316;
		default: goto yy48;
	}
yy291:
	yych = *++input->current;
	switch (yych) {
		case 'e': goto yy317;
		default: goto yy48;
	}
yy292:
	yych = *++input->current;
	switch (yych) {
		case 'a': goto yy319;
		default: goto yy48;
	}
yy293:
	yych = *++input->current;
	switch (yych) {
		case 'e': goto yy320;
		default: goto yy48;
	}
yy294:
	yych = *++input->current;
	switch (yych) {
		case 't': goto yy322;
		default: goto yy48;
	}
yy295:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy296;
	}
yy296:
#line 248 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, RETURN); continue; }
#line 4427 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy297:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy298;
	}
yy298:
#line 278 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, STRING); continue; }
#line 4499 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy299:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy300;
	}
yy300:
#line 269 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, UINT16); continue; }
#line 4571 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy301:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy302;
	}
yy302:
#line 270 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, UINT32); continue; }
#line 4643 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy303:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy304;
	}
yy304:
#line 271 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, UINT64); continue; }
#line 4715 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy305:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy306;
	}
yy306:
#line 260 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, UNSAFE); continue; }
#line 4787 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy307:
	yych = *++input->current;
	switch (yych) {
		case 't': goto yy323;
		default: goto yy48;
	}
yy308:
	yych = *++input->current;
	switch (yych) {
		case 'e': goto yy325;
		default: goto yy48;
	}
yy309:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy310;
	}
yy310:
#line 242 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, EXTENDS); continue; }
#line 4871 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy311:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy312;
	}
yy312:
#line 272 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, FLOAT32); continue; }
#line 4943 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy313:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy314;
	}
yy314:
#line 273 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, FLOAT64); continue; }
#line 5015 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy315:
	yych = *++input->current;
	switch (yych) {
		case 'n': goto yy327;
		default: goto yy48;
	}
yy316:
	yych = *++input->current;
	switch (yych) {
		case 'n': goto yy329;
		default: goto yy48;
	}
yy317:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy318;
	}
yy318:
#line 235 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, INCLUDE); continue; }
#line 5099 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy319:
	yych = *++input->current;
	switch (yych) {
		case 'c': goto yy330;
		default: goto yy48;
	}
yy320:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy321;
	}
yy321:
#line 236 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, PRIVATE); continue; }
#line 5177 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy322:
	yych = *++input->current;
	switch (yych) {
		case 'e': goto yy331;
		default: goto yy48;
	}
yy323:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy324;
	}
yy324:
#line 244 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, ABSTRACT); continue; }
#line 5255 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy325:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy326;
	}
yy326:
#line 255 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, CONTINUE); continue; }
#line 5327 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy327:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy328;
	}
yy328:
#line 276 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, FUNCTION); continue; }
#line 5399 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy329:
	yych = *++input->current;
	switch (yych) {
		case 't': goto yy332;
		default: goto yy48;
	}
yy330:
	yych = *++input->current;
	switch (yych) {
		case 'e': goto yy333;
		default: goto yy48;
	}
yy331:
	yych = *++input->current;
	switch (yych) {
		case 'd': goto yy335;
		default: goto yy48;
	}
yy332:
	yych = *++input->current;
	switch (yych) {
		case 's': goto yy337;
		default: goto yy48;
	}
yy333:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy334;
	}
yy334:
#line 240 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, INTERFACE); continue; }
#line 5495 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy335:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy336;
	}
yy336:
#line 237 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, PROTECTED); continue; }
#line 5567 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
yy337:
	yych = *++input->current;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy47;
		default: goto yy338;
	}
yy338:
#line 243 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"
	{ _append_token(stream, IMPLEMENTS); continue; }
#line 5639 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.c"
}
#line 325 "/Users/spencernold/Documents/Workspaces/GitHub/tlang/src/lexer.re"

    }
    return stream;
}

token_t* lex_stream_next(lex_token_stream_t* stream) {
    return poll_tok_queue(stream->queue);
}

void lex_free_token(token_t* token) {
    free_token(token);
}

void lex_close_token_stream(lex_token_stream_t* stream) {
    free_tok_queue(stream->queue);
    free(stream);
}